export const videoConfig = [
  {
    id: 1,
    title: 'オープニング',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_0.mp4`,
    detailButton: null,
    ctaButton: null,
    subtitles: [
      { start: 0, end: 3, text: 'ようこそアループクリニックへ。' },
      { start: 4, end: 7, text: '医療からも、美容からも、最適解を。' },
      { start: 8, end: 9, text: '科学的根拠に基づいた、' },
      {
        start: 10,
        end: 13,
        text: 'あなたにぴったりの施術プランをご案内いたします。',
      },
      { start: 14, end: 18, text: '詳しく知りたい内容を選択してください。' },
    ],
  },
  {
    id: 2,
    title: 'アループクリニックの特徴',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_1.mp4`,
    detailButton: {
      text: '詳細はこちら',
      link: 'https://aloop.clinic/about/',
    },
    ctaButton: {
      text: '予約する',
      link: 'https://aloop.b4a.clinic/clinics/170/bookings/new/select/',
    },
    subtitles: [
      { start: 0, end: 2, text: '肌理論研究に長年向き合ってきた' },
      { start: 3, end: 6, text: 'ポーラ化成が全面的に協力。' },
      { start: 7, end: 8, text: '研究レベルの肌分析で、' },
      { start: 9, end: 12, text: 'あなただけの最適なプランをご提案します。' },
      { start: 13, end: 15, text: 'たるみ、シミ、毛穴など、' },
      { start: 16, end: 17, text: 'あらゆるお悩みに' },
      { start: 18, end: 19, text: '医師による的確な施術で、' },
      { start: 20, end: 23, text: '本質的なケアをご提案いたします。' },
    ],
  },
  {
    id: 3,
    title: '院長・医師の紹介',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_2.mp4`,
    detailButton: {
      text: '詳細はこちら',
      link: 'https://aloop.clinic/about/',
    },
    ctaButton: null,
    subtitles: [
      { start: 0, end: 3, text: '皮膚科学の最前線を率いてきた山﨑院長は、' },
      { start: 4, end: 6, text: '皮膚疾患のメカニズムを熟知する、' },
      { start: 7, end: 9, text: '肌のプロフェッショナルです。' },
      {
        start: 10,
        end: 13,
        text: '医師たちも、エイジングケアから美肌治療まで、',
      },
      {
        start: 14,
        end: 16,
        text: 'それぞれの専門知識を持つプロフェッショナル。',
      },
      { start: 17, end: 20, text: 'チームで、あなただけの最適解を導きます。' },
      { start: 21, end: 22, text: 'お肌のことは、' },
      {
        start: 23,
        end: 27,
        text: 'アループクリニックの専門家チームへご相談ください。',
      },
    ],
  },
  {
    id: 4,
    title: '予約から診察の流れ',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_3.mp4`,
    detailButton: null,
    ctaButton: {
      text: '予約する',
      link: 'https://aloop.b4a.clinic/clinics/170/bookings/new/select/',
    },
    subtitles: [
      { start: 0, end: 4, text: 'WEBで1分、プランと日時を選ぶだけ。' },
      {
        start: 5,
        end: 9,
        text: '予約当日は銀座のクリニックへお越しください。',
      },
      { start: 10, end: 11, text: '「肌分析プラン」では、' },
      { start: 12, end: 16, text: 'まず専用ラボで30分かけて肌を精密測定。' },
      { start: 17, end: 19, text: '医師が科学的データに基づき、' },
      {
        start: 20,
        end: 24,
        text: 'あなただけの美肌戦略を丁寧にプランニングします。',
      },
      { start: 25, end: 26, text: '「セルフセレクトプラン」では、' },
      { start: 27, end: 30, text: '医師が診察した後、ご希望の施術へ。' },
      { start: 31, end: 33, text: 'カウンセリングで不安を解消し、' },
      { start: 34, end: 37, text: '安心して施術を受けていただけます。' },
    ],
  },
  {
    id: 5,
    title: '料金プランについて',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_4.mp4`,
    detailButton: {
      text: '詳細はこちら',
      link: 'https://aloop.clinic/about/',
    },
    ctaButton: {
      text: '予約する',
      link: 'https://aloop.b4a.clinic/clinics/170/bookings/new/select/',
    },
    subtitles: [
      {
        start: 0,
        end: 5,
        text: 'アループクリニックは、無理なく続けられる料金体系です。',
      },
      { start: 6, end: 9, text: 'まずは「ALOOP肌分析プラン」。' },
      { start: 10, end: 12, text: '研究レベルの分析とプランニング、' },
      {
        start: 13,
        end: 18,
        text: 'トライアルのピーリングまで含めて、19,800円です。',
      },
      {
        start: 19,
        end: 23,
        text: 'コース契約はなく、お支払いは安心の都度払い。',
      },
      { start: 24, end: 26, text: 'ピーリング9,900円から、' },
      { start: 27, end: 31, text: 'ご希望の施術だけを選ぶことも可能です。' },
    ],
  },
  {
    id: 6,
    title: '施術ラインナップ',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_5.mp4`,
    detailButton: {
      text: '詳細はこちら',
      link: 'https://aloop.clinic/about/',
    },
    ctaButton: {
      text: '予約する',
      link: 'https://aloop.b4a.clinic/clinics/170/bookings/new/select/',
    },
    subtitles: [
      { start: 0, end: 4, text: 'たるみ、シミ、毛穴、ニキビ跡。' },
      { start: 5, end: 6, text: 'つきない肌悩みに、' },
      { start: 7, end: 10, text: '豊富な施術ラインナップでお応えします。' },
      { start: 11, end: 11, text: 'たるみには、' },
      { start: 12, end: 16, text: '新型の医療ハイフや高周波治療。' },
      { start: 17, end: 18, text: 'シミやくすみには、' },
      { start: 19, end: 21, text: 'ダメージを抑えたピコレーザーや光治療を。' },
      { start: 22, end: 23, text: '毛穴やニキビ跡には、' },
      {
        start: 24,
        end: 29,
        text: '肌再生を促すマイクロニードルRFや各種ピーリング。',
      },
      { start: 30, end: 32, text: 'あなたの肌質や悩みに合わせ、' },
      { start: 33, end: 37, text: '医師が最適な施術をご提案いたします。' },
    ],
  },
  {
    id: 7,
    title: 'おすすめの施術',
    videoUrl: `${import.meta.env.VITE_BASE_URL}/aloop/ayumi_6.mp4`,
    detailButton: {
      text: '詳細はこちら',
      link: 'https://aloop.clinic/about/',
    },
    ctaButton: {
      text: '予約する',
      link: 'https://aloop.b4a.clinic/clinics/170/bookings/new/select/',
    },
    subtitles: [
      { start: 0, end: 2, text: '自分に合う施術がわからない。' },
      { start: 3, end: 5, text: 'そんな経験ありませんか？' },
      { start: 6, end: 7, text: 'アループクリニックでは、' },
      {
        start: 8,
        end: 12,
        text: 'まず、あなたの肌を科学的に知ることから始まります。',
      },
      { start: 13, end: 15, text: '「ALOOP肌分析プラン」は、' },
      { start: 16, end: 17, text: '研究レベルの精密な測定で、' },
      { start: 18, end: 20, text: '肌のポテンシャルを分析。' },
      { start: 21, end: 23, text: '医師がその科学的データに基づき、' },
      { start: 24, end: 26, text: 'あなただけのプランをご提案します。' },
      { start: 27, end: 31, text: 'もう、施術選びで迷うことはありません。' },
    ],
  },
]
